In [1]:
import numpy as np

In [11]:
arr = np.array([1,2, 4, 10, 50, 100, 200, 2000, 1000, 3000])


In [12]:
sd = np.std(arr)
print("SD: ", sd)
stdv = (arr - np.mean(arr))/sd
print(stdv)

SD:  999.9376030533106
[-0.63573967 -0.63473961 -0.63273948 -0.62673911 -0.58673661 -0.53673349
 -0.43672725  1.36338507  0.36332267  2.36344747]


In [13]:
np.std(stdv)

1.0

In [14]:
np.mean(stdv)

-4.4408920985006264e-17

In [15]:
np.std([1])

0.0

In [16]:
np.mean([1])

1.0

In [18]:
arr = np.array([1])
sd = np.std(arr)
print("SD: ", sd)
stdv = (arr - np.mean(arr))/(sd + 1e-10)
print(stdv)

SD:  0.0
[0.]


In [26]:
arr = np.array([[1,2,3], [3, 4, 5],[3,3,2], [1,2,3,4],[10]])
mean = 0
sd = 0
for i in range(len(arr)):
    mean = 0.8*mean + 0.2*np.mean(arr[i])
    sd = 0.8*sd + 0.2*np.std(arr[i])
    print(f"mean: {mean}, sd: {sd}")
    sarr = (arr[i] - mean)/sd
    print(sarr)
    

mean: 0.4, sd: 0.16329931618554522
[ 3.67423461  9.79795897 15.92168333]
mean: 1.12, sd: 0.2939387691339814
[ 6.39588988  9.79795897 13.20002806]
mean: 1.4293333333333336, sd: 0.3294319194653915
[4.76780352 4.76780352 1.73227496]
mean: 1.6434666666666669, sd: 0.48715233332229224
[-1.32087362  0.73187237  2.78461836  4.83736436]
mean: 3.3147733333333336, sd: 0.3897218666578338
[17.15384031]


/usr/local/anaconda/envs/tensorflow2/lib/python3.6/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.
