Gradient Descent Discussion:
    
    https://docs.google.com/spreadsheets/d/1xFRgnbdRc7dyaVUPT5kTlNKGALzjc8OutWkeumcrbe0/edit?gid=0#gid=0
        
Building RAG:

VectorStore:
    - ChromaDB
    - Quadrant

Ollama 
    - install llma3 - model
    - python library

---

Take the documents:
    extract text:
        split it into chunks
            compute the chunks embedding using LLM's api
            Store in Vector Store

---

Answer the query:
    - Compute the embedding using LLM
    - Look up Vector Store for closest embeddings and get the chunk
    - Compose the response using LLM:
        - Here is the document
        - please answer user's question using this.



In [4]:
import numpy as np

In [3]:
# Creating Data Set

# def create_data(m, n=1):
m, n = 10, 3
X = np.random.random((m, n))

In [4]:
X

array([[0.54950725, 0.45318657, 0.24153653],
       [0.91124644, 0.70388631, 0.36839805],
       [0.810235  , 0.09230793, 0.7309855 ],
       [0.3652396 , 0.95441582, 0.18504102],
       [0.77549699, 0.00827097, 0.29337307],
       [0.56444353, 0.71137137, 0.03896386],
       [0.39579223, 0.28398921, 0.79648646],
       [0.32168493, 0.41640525, 0.82645607],
       [0.55670396, 0.65343612, 0.44803954],
       [0.4682833 , 0.86106257, 0.48054755]])

In [14]:
np.random.seed(11)
w = np.random.random_integers(-20, 20, n+1)
w

/usr/local/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: This function is deprecated. Please call randint(-20, 20 + 1) instead
  


array([ 5, -4,  7, -3])

In [15]:
w

array([ 5, -4,  7, -3])

In [34]:
np.array([1,2,3, 4, 5, 6]).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
np.array([1,2,3, 4, 5, 6]).reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
np.array([1,2,3, 4, 5, 6]).reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
np.array([1,2,3, 4, 5, 6]).reshape(-1,-1)

ValueError: can only specify one unknown dimension

In [45]:
np.array([1,2,3, 4, 5, 6]).reshape(1, -1)

array([[1, 2, 3, 4, 5, 6]])

In [46]:
np.array([1,2,3, 4, 5, 6]).reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [47]:
np.array([1, 2, 3, 4, 5, 6]).reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [52]:
np.array([1, 2, 3, 4, 5, 6]).reshape(1, 1, -1)

array([[[1, 2, 3, 4, 5, 6]]])

In [53]:
np.array([1, 2, 3, 4, 5, 6]).reshape(1, 1, -2)

array([[[1, 2, 3, 4, 5, 6]]])

In [48]:
weights = w[:-1]
print(weights)
weights = weights.reshape(-1, 1)
print(weights)
# weights.T

[ 5 -4  7]
[[ 5]
 [-4]
 [ 7]]


In [64]:
print(w)
weights = w[:-1]
print(weights)
weights = weights.reshape(1, -1)
print(weights)
weights.T

[ 5 -4  7 -3]
[ 5 -4  7]
[[ 5 -4  7]]


array([[ 5],
       [-4],
       [ 7]])

In [65]:
print(w)
weights = w[:-1]
print(weights)
weights = weights.reshape(-1, 1)
print(weights)

[ 5 -4  7 -3]
[ 5 -4  7]
[[ 5]
 [-4]
 [ 7]]


In [72]:
y1 = X.dot(weights)
print(y1)

[[ 2.62554568]
 [ 4.31947327]
 [ 8.79884184]
 [-0.69617811]
 [ 5.89801255]
 [ 0.24947917]
 [ 6.41840952]
 [ 5.72799616]
 [ 3.30605212]
 [ 2.26099903]]


In [71]:
y1 + w[-1]

array([[-0.37445432],
       [ 1.31947327],
       [ 5.79884184],
       [-3.69617811],
       [ 2.89801255],
       [-2.75052083],
       [ 3.41840952],
       [ 2.72799616],
       [ 0.30605212],
       [-0.73900097]])

In [55]:
np.array([1, 2, 3, 4, 5, 6]).reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [50]:
y = X.dot(weights) 
y # m x 1

array([[ 2.62554568],
       [ 4.31947327],
       [ 8.79884184],
       [-0.69617811],
       [ 5.89801255],
       [ 0.24947917],
       [ 6.41840952],
       [ 5.72799616],
       [ 3.30605212],
       [ 2.26099903]])

In [22]:
np.sum(np.array([0.54950725, 0.45318657, 0.24153653])*np.array([ 5, -4,  7]))

2.62554568

In [29]:
w[-1]

-3

In [28]:
X.dot(weights) + w[-1]

ValueError: shapes (10,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [5]:
def create_data(m, n=1):
    np.random.seed(11)
    X = np.random.random((m, n))
    w = np.random.randint(-20, 20, n+1)
    print("Generated weights: ", w)
    weights = w[:-1]
    weights = weights.reshape(n, 1)
    y1 = X.dot(weights)
    y = y1 + w[-1]
    return X, y

In [86]:
X, y = create_data(10, 3)

Generated weights:  [  7  11 -15 -13]


In [88]:
X, y

(array([[0.18026969, 0.01947524, 0.46321853],
        [0.72493393, 0.4202036 , 0.4854271 ],
        [0.01278081, 0.48737161, 0.94180665],
        [0.85079509, 0.72996447, 0.10873607],
        [0.89390417, 0.85715425, 0.16508662],
        [0.63233401, 0.02048361, 0.11673727],
        [0.31636731, 0.15791231, 0.75897959],
        [0.81827536, 0.34462449, 0.3187988 ],
        [0.11166123, 0.08395314, 0.71272594],
        [0.5995434 , 0.05567368, 0.47979728]]), array([[-18.47216242],
        [-10.58462932],
        [-21.6765464 ],
        [ -0.64586628],
        [  0.20972665],
        [-10.09940119],
        [-20.43308727],
        [ -8.26318505],
        [-21.98577583],
        [-15.38774498]]))

In [92]:
X.stack(np.ones((10, 1)))

AttributeError: 'numpy.ndarray' object has no attribute 'stack'

In [134]:
X

array([[0.18026969, 0.01947524, 0.46321853],
       [0.72493393, 0.4202036 , 0.4854271 ],
       [0.01278081, 0.48737161, 0.94180665],
       [0.85079509, 0.72996447, 0.10873607],
       [0.89390417, 0.85715425, 0.16508662],
       [0.63233401, 0.02048361, 0.11673727],
       [0.31636731, 0.15791231, 0.75897959],
       [0.81827536, 0.34462449, 0.3187988 ],
       [0.11166123, 0.08395314, 0.71272594],
       [0.5995434 , 0.05567368, 0.47979728]])

In [135]:
ones = np.ones((10,1))
ones

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [136]:
np.c_[X, ones]

array([[0.18026969, 0.01947524, 0.46321853, 1.        ],
       [0.72493393, 0.4202036 , 0.4854271 , 1.        ],
       [0.01278081, 0.48737161, 0.94180665, 1.        ],
       [0.85079509, 0.72996447, 0.10873607, 1.        ],
       [0.89390417, 0.85715425, 0.16508662, 1.        ],
       [0.63233401, 0.02048361, 0.11673727, 1.        ],
       [0.31636731, 0.15791231, 0.75897959, 1.        ],
       [0.81827536, 0.34462449, 0.3187988 , 1.        ],
       [0.11166123, 0.08395314, 0.71272594, 1.        ],
       [0.5995434 , 0.05567368, 0.47979728, 1.        ]])

In [6]:
def create_data_1(m, n=1):
    np.random.seed(10)
    X = np.random.random((m, n))
    w = np.random.randint(-20, 20, (1, n+1))
    ones = np.ones((m,1))
    X1 = np.c_[X, ones]
    print("Generated weights: ", w)
    y = X1.dot(w.T) + 2*np.random.random((m, 1)) - 2*np.random.random((m, 1))
    return X, y

In [164]:
X, y = create_data_1(1000, 3)

Generated weights:  [[ 16 -11  -9  -6]]


In [165]:
X, y

(array([[0.77132064, 0.02075195, 0.63364823],
        [0.74880388, 0.49850701, 0.22479665],
        [0.19806286, 0.76053071, 0.16911084],
        ...,
        [0.47965191, 0.91270225, 0.05617608],
        [0.70404929, 0.03809938, 0.13806513],
        [0.18444572, 0.74002493, 0.92104046]]), array([[ 8.84438585e-01],
        [-1.58958231e+00],
        [-1.17191636e+01],
        [-1.99272029e+01],
        [-1.81217620e+01],
        [-7.28788405e+00],
        [-4.39670919e+00],
        [-1.53115266e+01],
        [-8.71701857e+00],
        [-1.05714407e+01],
        [-6.85265983e+00],
        [-4.84450557e+00],
        [-1.49256906e+01],
        [-1.00104719e+01],
        [-1.62032191e+01],
        [-4.91273975e+00],
        [-5.10713931e+00],
        [-1.44057625e+01],
        [-1.94468583e+01],
        [-1.05947977e+01],
        [-1.28119228e+01],
        [ 6.43513454e-02],
        [-1.26707510e+01],
        [ 2.10908402e+00],
        [-1.00854587e+01],
        [-2.08548734e+01],
        

In [96]:
def loss(X, y, w):
    yp = X.dot(w.T)
    diff = yp - y
    sqdiff = diff**2
    return np.sum(sqdiff, axis=0)

In [135]:
X = np.array([[2, 1], [15, 1]])
y = np.array([[1], [16]])
w = np.array([[10.000001, 20], [10, 20.000001]])
loss(X, y, w)/.000001

array([2.52370048e+10, 2.52370004e+10])

In [49]:
yp = np.array([[1, 2], 
               [10, 20]])
y = np.array([[1, 2]])
print(yp-y)

[[ 0  0]
 [ 9 18]]


In [50]:
yp = np.array([[1, 2], 
               [10, 20]])
y = np.array([[1], 
              [2]])
print(yp-y)

[[ 0  1]
 [ 8 18]]


In [ ]:
[10, 20, 30]
-->
[ 
    [10.0000001, 20, 30],
    [10, 20.00000001, 30],
    [10, 20, 30.0000001]
]

In [73]:
w = np.array([10, 20, 30])
delta = 0.000001
lw = w.shape[0]
np.diag(np.zeros(lw,) + delta) + w

array([[10.000001, 20.      , 30.      ],
       [10.      , 20.000001, 30.      ],
       [10.      , 20.      , 30.000001]])

In [75]:
w = np.array([10, 20, 30])
w.shape[0]

3

In [76]:
np.diag(np.zeros(3) + 0.01) + np.array([10, 20, 30])

array([[10.01, 20.  , 30.  ],
       [10.  , 20.01, 30.  ],
       [10.  , 20.  , 30.01]])

In [64]:
np.diag([10, 20, 30])

array([[10,  0,  0],
       [ 0, 20,  0],
       [ 0,  0, 30]])

In [150]:
w.shape

(1, 4)

In [151]:
w

array([[12.28873174, -9.36704428, -7.99806444, -5.45189152]])

In [161]:
delta = 0.00000001
lw = w.shape[1]
print(lw)
new_ws = np.diag(np.zeros(lw) + delta) + w
print(new_ws)

4
[[12.28873175 -9.36704428 -7.99806444 -5.45189152]
 [12.28873174 -9.36704427 -7.99806444 -5.45189152]
 [12.28873174 -9.36704428 -7.99806443 -5.45189152]
 [12.28873174 -9.36704428 -7.99806444 -5.45189151]]


In [181]:
def gradients(X,  y, w):
    initialloss = loss(X, y, w)[0]
    print("Initial Loss: ", initialloss)
    delta = 1e-10
    lw = w.shape[1]
    new_ws = np.diag(np.zeros(lw) + delta) + w
    new_losses = loss(X, y, new_ws)
    print("new_losses: ", new_losses)
    return (new_losses - initialloss)/delta

In [182]:
n=3
np.random.random((1, n+1))

array([[0.07609689, 0.45780079, 0.75296266, 0.97480353]])

In [183]:
# Get X, y - Data
X, y = create_data_1(1000, 3)

Generated weights:  [[ 16 -11  -9  -6]]


In [184]:
X

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.49850701, 0.22479665],
       [0.19806286, 0.76053071, 0.16911084],
       ...,
       [0.47965191, 0.91270225, 0.05617608],
       [0.70404929, 0.03809938, 0.13806513],
       [0.18444572, 0.74002493, 0.92104046]])

In [185]:
m, n = X.shape
ones = np.ones((m,1))
X = np.c_[X, ones]

In [186]:
m, n

(1000, 3)

In [187]:
X.shape, y.shape, w.shape

((1000, 4), (1000, 1), (1, 4))

In [188]:
eta = 0.0001

# X1 = add 1 to X.

w = np.random.random((1, n+1))

In [190]:
for epoch in range(1000):
    print("===== EPOCH =======", epoch)
    #compute gradients
    grads = gradients(X, y , w)
    print("grads: ", grads)

    # update the weights in proporation to the gradient
    w = w - eta * grads
    print("Final Loss: ", loss(X, y, w))

===== EPOCH ======= 0
Initial Loss:  2071.842357538892
new_losses:  [2071.84235748 2071.84235757 2071.84235756 2071.84235754]
grads:  [-575.71924117  287.33211366  191.28492568   44.70166459]
Final Loss:  [2026.94867557]
===== EPOCH ======= 1
Initial Loss:  2026.9486755730811
new_losses:  [2026.94867552 2026.9486756  2026.94867559 2026.94867558]
grads:  [-566.63793657  282.60046747  187.59010345   44.39243639]
Final Loss:  [1983.49440971]
===== EPOCH ======= 2
Initial Loss:  1983.494409714959
new_losses:  [1983.49440966 1983.49440974 1983.49440973 1983.49440972]
grads:  [-557.6202966   277.96204449  183.9862307    44.10594556]
Final Loss:  [1941.4367086]
===== EPOCH ======= 3
Initial Loss:  1941.4367086025304
new_losses:  [1941.43670855 1941.43670863 1941.43670862 1941.43670861]
grads:  [-548.83230405  273.39865483  180.41873773   43.8421921 ]
Final Loss:  [1900.72630894]
===== EPOCH ======= 4
Initial Loss:  1900.7263089381076
new_losses:  [1900.72630888 1900.72630896 1900.72630896 190

Initial Loss:  716.1615793104097
new_losses:  [716.1615793  716.16157932 716.16157931 716.16157931]
grads:  [-113.70048014   50.19728633   22.20531314   20.35108082]
Final Loss:  [714.53879518]
===== EPOCH ======= 104
Initial Loss:  714.5387951815334
new_losses:  [714.53879517 714.53879519 714.53879518 714.53879518]
grads:  [-111.96334526   49.33326636   21.69258551   20.16804501]
Final Loss:  [712.96651665]
===== EPOCH ======= 105
Initial Loss:  712.9665166482223
new_losses:  [712.96651664 712.96651665 712.96651665 712.96651665]
grads:  [-110.25349522   48.47947821   21.19236342   19.99865162]
Final Loss:  [711.44314151]
===== EPOCH ======= 106
Initial Loss:  711.4431415125293
new_losses:  [711.4431415  711.44314152 711.44314151 711.44314151]
grads:  [-108.54364518   47.65183803   20.70578375   19.83266884]
Final Loss:  [709.96734701]
===== EPOCH ======= 107
Initial Loss:  709.9673470092728
new_losses:  [709.967347   709.96734701 709.96734701 709.96734701]
grads:  [-106.8963229    46.

Initial Loss:  665.7219734920166
new_losses:  [665.72197349 665.72197349 665.72197349 665.72197349]
grads:  [-24.57795745   7.90691956   0.53432814   8.14793566]
Final Loss:  [665.64919209]
===== EPOCH ======= 205
Initial Loss:  665.6491920943995
new_losses:  [665.64919209 665.6491921  665.64919209 665.6491921 ]
grads:  [-24.21415957   7.75003173   0.47066351   8.07290235]
Final Loss:  [665.5785343]
===== EPOCH ======= 206
Initial Loss:  665.5785343048879
new_losses:  [665.5785343  665.57853431 665.5785343  665.57853431]
grads:  [-23.85604603   7.60337571   0.41723069   7.99104782]
Final Loss:  [665.50993556]
===== EPOCH ======= 207
Initial Loss:  665.5099355626227
new_losses:  [665.50993556 665.50993556 665.50993556 665.50993556]
grads:  [-23.50247996   7.45899342   0.37289283   7.92283572]
Final Loss:  [665.44332588]
===== EPOCH ======= 208
Initial Loss:  665.4433258827273
new_losses:  [665.44332588 665.44332588 665.44332588 665.44332588]
grads:  [-23.15459824   7.3123374    0.331965

Initial Loss:  663.2585227152379
new_losses:  [663.25852271 663.25852272 663.25852272 663.25852272]
grads:  [-5.14432941  0.63096195 -1.04478204  2.84785528]
Final Loss:  [663.25493851]
===== EPOCH ======= 314
Initial Loss:  663.2549385065475
new_losses:  [663.25493851 663.25493851 663.25493851 663.25493851]
grads:  [-5.07384357  0.61618266 -1.0425083   2.82057044]
Final Loss:  [663.2514442]
===== EPOCH ======= 315
Initial Loss:  663.2514441961015
new_losses:  [663.2514442 663.2514442 663.2514442 663.2514442]
grads:  [-5.00335773  0.58435035 -1.0425083   2.78191692]
Final Loss:  [663.24804189]
===== EPOCH ======= 316
Initial Loss:  663.2480418872839
new_losses:  [663.24804189 663.24804189 663.24804189 663.24804189]
grads:  [-4.9396931   0.57298166 -1.03682396  2.77964318]
Final Loss:  [663.2447158]
===== EPOCH ======= 317
Initial Loss:  663.244715800745
new_losses:  [663.2447158 663.2447158 663.2447158 663.2447158]
grads:  [-4.87375473  0.56729732 -1.03113962  2.73075784]
Final Loss:  

Final Loss:  [663.12259466]
===== EPOCH ======= 418
Initial Loss:  663.1225946584798
new_losses:  [663.12259466 663.12259466 663.12259466 663.12259466]
grads:  [-1.27215571 -0.12732926 -0.53432814  1.00158104]
Final Loss:  [663.12230424]
===== EPOCH ======= 419
Initial Loss:  663.1223042367583
new_losses:  [663.12230424 663.12230424 663.12230424 663.12230424]
grads:  [-1.24941835 -0.129603   -0.54001248  0.99134922]
Final Loss:  [663.12202058]
===== EPOCH ======= 420
Initial Loss:  663.1220205755728
new_losses:  [663.12202058 663.12202058 663.12202058 663.12202058]
grads:  [-1.23122845 -0.14665602 -0.52523319  0.98680175]
Final Loss:  [663.12174331]
===== EPOCH ======= 421
Initial Loss:  663.1217433136806
new_losses:  [663.12174331 663.12174331 663.12174331 663.12174331]
grads:  [-1.20053301 -0.13756107 -0.52068572  0.97202246]
Final Loss:  [663.12147465]
===== EPOCH ======= 422
Initial Loss:  663.121474649857
new_losses:  [663.12147465 663.12147465 663.12147465 663.12147465]
grads:  [

new_losses:  [663.11049221 663.11049221 663.11049221 663.11049221]
grads:  [-0.33878678 -0.11482371 -0.18985702  0.31604941]
Final Loss:  [663.1104655]
===== EPOCH ======= 528
Initial Loss:  663.1104654987985
new_losses:  [663.1104655 663.1104655 663.1104655 663.1104655]
grads:  [-0.32173375 -0.09890755 -0.21486812  0.33310243]
Final Loss:  [663.11043873]
===== EPOCH ======= 529
Initial Loss:  663.1104387252208
new_losses:  [663.11043873 663.11043873 663.11043873 663.11043873]
grads:  [-0.32059688 -0.10231815 -0.20349944  0.32969183]
Final Loss:  [663.11041257]
===== EPOCH ======= 530
Initial Loss:  663.1104125736209
new_losses:  [663.11041257 663.11041257 663.11041257 663.11041257]
grads:  [-0.32741809 -0.1080025  -0.20349944  0.3092282 ]
Final Loss:  [663.11038707]
===== EPOCH ======= 531
Initial Loss:  663.1103870742528
new_losses:  [663.11038707 663.11038707 663.11038707 663.11038707]
grads:  [-0.32173375 -0.10004442 -0.19213076  0.32855496]
Final Loss:  [663.11036172]
===== EPOCH 

new_losses:  [663.10932193 663.10932193 663.10932193 663.10932193]
grads:  [-0.09549694 -0.03865352 -0.08753887  0.12732926]
Final Loss:  [663.10931874]
===== EPOCH ======= 634
Initial Loss:  663.1093187445545
new_losses:  [663.10931874 663.10931874 663.10931874 663.10931874]
grads:  [-0.10686563 -0.03979039 -0.07389644  0.11368684]
Final Loss:  [663.10931574]
===== EPOCH ======= 635
Initial Loss:  663.109315735202
new_losses:  [663.10931574 663.10931574 663.10931574 663.10931574]
grads:  [-0.09322321 -0.04092726 -0.06366463  0.11254997]
Final Loss:  [663.10931296]
===== EPOCH ======= 636
Initial Loss:  663.1093129645172
new_losses:  [663.10931296 663.10931296 663.10931296 663.10931296]
grads:  [-0.09322321 -0.05002221 -0.06366463  0.11596057]
Final Loss:  [663.10931014]
===== EPOCH ======= 637
Initial Loss:  663.1093101439287
new_losses:  [663.10931014 663.10931014 663.10931014 663.10931014]
grads:  [-0.09777068 -0.03751666 -0.0648015   0.10004442]
Final Loss:  [663.10930753]
===== EP

Final Loss:  [663.10918892]
===== EPOCH ======= 750
Initial Loss:  663.109188916125
new_losses:  [663.10918892 663.10918892 663.10918892 663.10918892]
grads:  [-0.02955858 -0.00113687 -0.01023182  0.03979039]
Final Loss:  [663.10918868]
===== EPOCH ======= 751
Initial Loss:  663.1091886812301
new_losses:  [663.10918868 663.10918868 663.10918868 663.10918868]
grads:  [-0.01477929 -0.02387424 -0.01818989  0.03637979]
Final Loss:  [663.10918844]
===== EPOCH ======= 752
Initial Loss:  663.1091884436212
new_losses:  [663.10918844 663.10918844 663.10918844 663.10918844]
grads:  [-0.03069545 -0.02842171 -0.01250555  0.02728484]
Final Loss:  [663.10918819]
===== EPOCH ======= 753
Initial Loss:  663.1091881940672
new_losses:  [663.10918819 663.10918819 663.10918819 663.10918819]
grads:  [-0.0250111  -0.0216005  -0.02387424  0.03183231]
Final Loss:  [663.10918794]
===== EPOCH ======= 754
Initial Loss:  663.109187936357
new_losses:  [663.10918794 663.10918794 663.10918794 663.10918794]
grads:  [-

Initial Loss:  663.1091770616779
new_losses:  [663.10917706 663.10917706 663.10917706 663.10917706]
grads:  [ 0.00682121 -0.00795808 -0.00795808  0.01023182]
Final Loss:  [663.10917705]
===== EPOCH ======= 862
Initial Loss:  663.1091770459502
new_losses:  [663.10917705 663.10917705 663.10917705 663.10917705]
grads:  [-0.01250555 -0.00227374 -0.00909495  0.00227374]
Final Loss:  [663.10917703]
===== EPOCH ======= 863
Initial Loss:  663.1091770269288
new_losses:  [663.10917703 663.10917703 663.10917703 663.10917703]
grads:  [-0.00568434 -0.01818989 -0.01818989  0.01023182]
Final Loss:  [663.10917699]
===== EPOCH ======= 864
Initial Loss:  663.1091769914929
new_losses:  [663.10917699 663.10917699 663.10917699 663.10917699]
grads:  [-0.00568434 -0.01591616  0.00909495  0.01932676]
Final Loss:  [663.10917696]
===== EPOCH ======= 865
Initial Loss:  663.1091769632187
new_losses:  [663.10917696 663.10917696 663.10917696 663.10917696]
grads:  [-0.00341061 -0.00909495 -0.00341061  0.00795808]
Fi

Initial Loss:  663.1091760237955
new_losses:  [663.10917602 663.10917602 663.10917602 663.10917602]
grads:  [ 0.00227374 -0.00909495 -0.00113687 -0.00568434]
Final Loss:  [663.10917602]
===== EPOCH ======= 972
Initial Loss:  663.1091760233829
new_losses:  [663.10917602 663.10917602 663.10917602 663.10917602]
grads:  [-0.01591616 -0.00113687 -0.00568434  0.00341061]
Final Loss:  [663.10917602]
===== EPOCH ======= 973
Initial Loss:  663.1091760170782
new_losses:  [663.10917602 663.10917602 663.10917602 663.10917602]
grads:  [-0.00227374 -0.00795808  0.          0.00682121]
Final Loss:  [663.10917601]
===== EPOCH ======= 974
Initial Loss:  663.1091760127188
new_losses:  [663.10917601 663.10917601 663.10917601 663.10917601]
grads:  [ 0.         -0.00454747  0.00227374  0.00227374]
Final Loss:  [663.10917601]
===== EPOCH ======= 975
Initial Loss:  663.1091760117849
new_losses:  [663.10917601 663.10917601 663.10917601 663.10917601]
grads:  [-0.00454747 -0.00341061  0.00568434  0.00795808]
Fi

In [191]:
w

array([[ 16.04433365, -10.99975845,  -8.97275383,  -6.01188549]])

In [ ]:
 [[ 16 -11  -9  -6]]